services: 
  finance-api:
    container_name: finance-api
    image: bitnami/postgresql
    ports: 
      - 5432:5432
    environment: 
      POSTGRESQL_USERNAME: ${DATABASE_USERNAME}
      POSTGRESQL_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRESQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - finance_api_data:/bitnami/postgresql
volumes:
  finance_api_data: