services: 
  finance-api:
    container_name: finance-api
    image: bitnami/postgresql
    ports: 
      - 5432:5432
    environment: 
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=financeapi
    volumes:
      - finance_api_data:/bitnami/postgresql
volumes:
  finance_api_data: