name: Run E2E Tests

on: [push]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          POSTGRESQL_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          POSTGRESQL_DATABASE: ${{ secrets.DATABASE_NAME }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - run: npm ci

      - run: npm run test:e2e
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          FINANCE_APP_TOKEN: ${{ secrets.FINANCE_APP_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
          PORT: ${{ secrets.PORT }}
